module.exports = {
    content: ["src/**/*.{ts,html,css,scss}", "./index.html"],
    theme: {
        fontFamily: {
            sans: ["Outfit", "sans-serif"],
        },
        extend: {
            colors: {
                "primary-50": "var(--lumine-primary-50)",
                "primary-100": "var(--lumine-primary-100)",
                "primary-200": "var(--lumine-primary-200)",
                "primary-300": "var(--lumine-primary-300)",
                "primary-400": "var(--lumine-primary-400)",
                "primary-500": "var(--lumine-primary-500)",
                "primary-600": "var(--lumine-primary-600)",
                "primary-700": "var(--lumine-primary-700)",
                "primary-800": "var(--lumine-primary-800)",
                "primary-900": "var(--lumine-primary-900)",
                "primary-text": "var(--lumine-primary-text)",

                "secondary-50": "var(--lumine-secondary-50)",
                "secondary-100": "var(--lumine-secondary-100)",
                "secondary-200": "var(--lumine-secondary-200)",
                "secondary-300": "var(--lumine-secondary-300)",
                "secondary-400": "var(--lumine-secondary-400)",
                "secondary-500": "var(--lumine-secondary-500)",
                "secondary-600": "var(--lumine-secondary-600)",
                "secondary-700": "var(--lumine-secondary-700)",
                "secondary-800": "var(--lumine-secondary-800)",
                "secondary-900": "var(--lumine-secondary-900)",
                "secondary-text": "var(--lumine-secondary-text)",

                "accent-50": "var(--lumine-accent-50)",
                "accent-100": "var(--lumine-accent-100)",
                "accent-200": "var(--lumine-accent-200)",
                "accent-300": "var(--lumine-accent-300)",
                "accent-400": "var(--lumine-accent-400)",
                "accent-500": "var(--lumine-accent-500)",
                "accent-600": "var(--lumine-accent-600)",
                "accent-700": "var(--lumine-accent-700)",
                "accent-800": "var(--lumine-accent-800)",
                "accent-900": "var(--lumine-accent-900)",
                "accent-text": "var(--lumine-accent-text)",

                "neutral-50": "var(--lumine-neutral-50)",
                "neutral-100": "var(--lumine-neutral-100)",
                "neutral-200": "var(--lumine-neutral-200)",
                "neutral-300": "var(--lumine-neutral-300)",
                "neutral-400": "var(--lumine-neutral-400)",
                "neutral-500": "var(--lumine-neutral-500)",
                "neutral-600": "var(--lumine-neutral-600)",
                "neutral-700": "var(--lumine-neutral-700)",
                "neutral-800": "var(--lumine-neutral-800)",
                "neutral-900": "var(--lumine-neutral-900)",
                "neutral-text": "var(--lumine-neutral-text)",

                "danger-50": "var(--lumine-danger-50)",
                "danger-100": "var(--lumine-danger-100)",
                "danger-200": "var(--lumine-danger-200)",
                "danger-300": "var(--lumine-danger-300)",
                "danger-400": "var(--lumine-danger-400)",
                "danger-500": "var(--lumine-danger-500)",
                "danger-600": "var(--lumine-danger-600)",
                "danger-700": "var(--lumine-danger-700)",
                "danger-800": "var(--lumine-danger-800)",
                "danger-900": "var(--lumine-danger-900)",
                "danger-text": "var(--lumine-danger-text)",

                "success-50": "var(--lumine-success-50)",
                "success-100": "var(--lumine-success-100)",
                "success-200": "var(--lumine-success-200)",
                "success-300": "var(--lumine-success-300)",
                "success-400": "var(--lumine-success-400)",
                "success-500": "var(--lumine-success-500)",
                "success-600": "var(--lumine-success-600)",
                "success-700": "var(--lumine-success-700)",
                "success-800": "var(--lumine-success-800)",
                "success-900": "var(--lumine-success-900)",
                "success-text": "var(--lumine-success-text)",

                "warning-50": "var(--lumine-warning-50)",
                "warning-100": "var(--lumine-warning-100)",
                "warning-200": "var(--lumine-warning-200)",
                "warning-300": "var(--lumine-warning-300)",
                "warning-400": "var(--lumine-warning-400)",
                "warning-500": "var(--lumine-warning-500)",
                "warning-600": "var(--lumine-warning-600)",
                "warning-700": "var(--lumine-warning-700)",
                "warning-800": "var(--lumine-warning-800)",
                "warning-900": "var(--lumine-warning-900)",
                "warning-text": "var(--lumine-warning-text)",

                "info-50": "var(--lumine-info-50)",
                "info-100": "var(--lumine-info-100)",
                "info-200": "var(--lumine-info-200)",
                "info-300": "var(--lumine-info-300)",
                "info-400": "var(--lumine-info-400)",
                "info-500": "var(--lumine-info-500)",
                "info-600": "var(--lumine-info-600)",
                "info-700": "var(--lumine-info-700)",
                "info-800": "var(--lumine-info-800)",
                "info-900": "var(--lumine-info-900)",
                "info-text": "var(--lumine-info-text)",

                "gray-50": "var(--lumine-gray-50)",
                "gray-100": "var(--lumine-gray-100)",
                "gray-200": "var(--lumine-gray-200)",
                "gray-300": "var(--lumine-gray-300)",
                "gray-400": "var(--lumine-gray-400)",
                "gray-500": "var(--lumine-gray-500)",

                "dark": "var(--lumine-dark)",
                "white": "var(--lumine-white)",
            },
        },
    },
    plugins: [],
};
